name: env2_conda
channels:
  - defaults
dependencies:
  - pip=19.3.1
  - python=2.7.18
  - pip:
      - biopython==1.74
      - numpy==1.16.6
      - pandas==0.24.2
      - scikit-learn==0.17.1
      - scipy==1.2.3
      - subprocess32==3.5.4
      - matplotlib==2.2.5